[package]
name = "bonesdeploy-core"
version = "0.8.7"
edition = "2024"
authors=["Alex Younger <thealexyounger@proton.me>"]
description="Deployments with a Spine in a Barebones Framework"
license="Apache-2.0"
repository="https://github.com/AlextheYounga/bonesdeploy"

[dependencies]
anyhow = "1.0.103"
getrandom = "0.4.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

[dev-dependencies]
tempfile = "3.27"

[lints]
workspace = true
