template: laravel
web_root: public
php_version: '8.5'
permissions:
  defaults:
    dir_mode: '750'
    file_mode: '640'
  paths:
    - path: 'storage'
      mode: '770'
      recursive: true
      type: 'dir'
    - path: 'bootstrap/cache'
      mode: '770'
      recursive: true
      type: 'dir'
    - path: 'database'
      mode: '770'
      recursive: false
      type: 'dir'
    - path: 'database/database.sqlite'
      mode: '660'
      recursive: false
      type: 'file'
shared:
  paths: 
    - path: 'storage'
      type: 'dir'
    - path: '.env'
      type: 'file'