---
- name: Check for rustup
  ansible.builtin.stat:
    path: "{{ rustup_install_prefix }}/rustup"
  register: common_rustup_binary
  tags: [common, bonesremote]

- name: Start rustup and cargo install
  ansible.builtin.shell: |
    set -euo pipefail
    curl --proto '=https' --tlsv1.2 -sSf {{ rustup_install_script_url }} | sh -s -- -y --profile minimal
  args:
    creates: "{{ rustup_install_prefix }}/cargo"
  when: not common_rustup_binary.stat.exists
  async: 1800
  poll: 0
  register: common_rustup_job
  tags: [common, bonesremote]
