template: sveltekit
web_root: build
permissions:
  defaults:
    dir_mode: '750'
    file_mode: '640'
  paths:
    - path: 'build'
      mode: '770'
      recursive: true
shared:
  paths:
    - path: '.env'
      type: 'file'
    - path: 'storage'
      type: 'dir'