[runtime]
template = "next"
web_root = "public"
node_version = "24.18.0"

[runtime.permissions]
paths = [
  { path = "*", type = "dir", mode = "750" },
  { path = "*", type = "file", mode = "640" },
  { path = ".next", type = "dir", mode = "770", recursive = true },
]
