---
nginx_package_name: nginx
nginx_service_name: nginx

nginx_site_name: "{{ project_name }}"
nginx_site_template_path: "{{ role_path }}/../../nginx/site-nginx.conf.j2"
nginx_site_service_template_path: "{{ role_path }}/../../nginx/site-nginx.service.j2"
nginx_router_template_path: "{{ role_path }}/../../nginx/router.conf.j2"
nginx_server_name: "_"
nginx_ssl_enabled: false
nginx_ssl_certificate_path: ""
nginx_ssl_certificate_key_path: ""

nginx_disable_default_site: true
