---
# Common role handlers

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: common_nginx_enabled

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
