template = "sveltekit"
web_root = "build"
build_image = "docker.io/library/node:24-bookworm"

[permissions]
paths = [
  { path = "*", type = "dir", mode = "750" },
  { path = "*", type = "file", mode = "640" },
  { path = "build", type = "dir", mode = "770", recursive = true },
]

[shared]
paths = [
  { path = ".env", type = "file" },
]
