---
# Variables for the common role

common_base_packages:
  - acl
  - age
  - apt-listchanges
  - apt-transport-https
  - automysqlbackup
  - autossh
  - btop
  - borgbackup
  - ca-certificates
  - curl
  - fail2ban
  - fastfetch
  - git
  - gnupg
  - htop
  - iftop
  - inotify-tools
  - iotop
  - jdupes
  - jq
  - lsb-release
  - lsof
  - moreutils
  - mutt
  - nano
  - neovim
  - ncdu
  - powerstat
  - powertop
  - rename
  - rsync
  - sqlite3
  - smartmontools
  - sysbench
  - sysstat
  - telnet
  - tmux
  - tree
  - unattended-upgrades
  - unzip
  - zip
  - zsh

# Nginx configuration
common_nginx_enabled: true

# Certbot/Let's Encrypt
common_certbot_enabled: true

# Docker ctop
common_ctop_enabled: true

# Tmux mouse mode
common_tmux_mouse_mode: true

# Unattended upgrades
common_unattended_upgrades_enabled: true
common_unattended_upgrades_mail: ""
common_unattended_upgrades_auto_reboot: false
common_unattended_upgrades_auto_reboot_time: "02:00"
common_unattended_upgrades_remove_unused_deps: true

# Fail2ban
common_fail2ban_enabled: true
common_fail2ban_sshd_enabled: true
common_fail2ban_backend: systemd
common_fail2ban_banaction: ufw
common_fail2ban_bantime: 1h
common_fail2ban_findtime: 10m
common_fail2ban_maxretry: 5
