[runtime]
template = "django"
web_root = "public"
node_version = "24.18.0"
python_version = "3.14"

[runtime.permissions]
paths = [
  { path = "*", type = "dir", mode = "750" },
  { path = "*", type = "file", mode = "640" },
  { path = "media", type = "dir", mode = "770", recursive = true },
]
