//! Per-site scheduled Borg backup configuration and its managed passphrase.

use std::fs;
use std::path::Path;

use anyhow::{Result, bail};
use serde::{Deserialize, Serialize};

/// Managed `.env` keys backing the backup configuration section.
pub(super) const SCHEDULE_KEY: &str = "BACKUP_SCHEDULE";
pub(super) const RETENTION_DAYS_KEY: &str = "BACKUP_RETENTION_DAYS";
pub(super) const PASSPHRASE_KEY: &str = "BORG_PASSPHRASE";

pub const BACKUP_SCHEDULE_DEFAULT: &str = "0 0 * * *";
pub const BACKUP_RETENTION_DAYS_DEFAULT: u16 = 30;

/// Upper bound for a single crontab field so malformed values are rejected
/// before they are rendered into `/etc/cron.d`.
const MAX_CRON_FIELD_LENGTH: usize = 64;

/// Per-site scheduled backup settings: the crontab schedule, the age-based
/// retention window, and the managed Borg repository passphrase.
///
/// An empty passphrase means backups are unconfigured; provisioning then keeps
/// the site's previous behavior.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct Backup {
    /// Five-field Linux crontab expression controlling the backup run.
    pub schedule: String,
    /// Archives older than this many days are pruned after each backup run.
    pub retention_days: u16,
    /// Borg repository passphrase. Generated by `bonesdeploy init` when absent.
    pub passphrase: String,
}

impl Default for Backup {
    fn default() -> Self {
        Self {
            schedule: BACKUP_SCHEDULE_DEFAULT.to_string(),
            retention_days: BACKUP_RETENTION_DAYS_DEFAULT,
            passphrase: String::new(),
        }
    }
}

impl Backup {
    /// True when the backup section carries a passphrase and should be provisioned.
    #[must_use]
    pub fn is_configured(&self) -> bool {
        !self.passphrase.trim().is_empty()
    }
}

/// # Errors
/// Returns an error when the schedule, retention, or passphrase is invalid.
pub fn validate_backup(backup: &Backup) -> Result<()> {
    validate_cron_expression(&backup.schedule)?;
    if backup.retention_days == 0 {
        bail!("backup retention must be at least one day");
    }
    validate_passphrase(&backup.passphrase)
}

/// # Errors
/// Returns an error when `schedule` is not a five-field crontab expression that
/// is safe to render into `/etc/cron.d`.
pub fn validate_cron_expression(schedule: &str) -> Result<()> {
    let fields = schedule.split_whitespace().collect::<Vec<_>>();
    if fields.len() != 5 {
        bail!("backup schedule must be a five-field crontab expression: `{schedule}`");
    }
    for field in fields {
        if field.len() > MAX_CRON_FIELD_LENGTH {
            bail!("backup schedule field is too long: `{field}`");
        }
        if !field.chars().all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '*' | '/' | ',' | '-')) {
            bail!("backup schedule field `{field}` contains unsupported characters");
        }
    }
    Ok(())
}

/// # Errors
/// Returns an error when the passphrase is set but not a single line of
/// printable ASCII without template or crontab metacharacters. Generated
/// passphrases are hexadecimal and always accepted.
fn validate_passphrase(passphrase: &str) -> Result<()> {
    if passphrase.trim().is_empty() {
        return Ok(());
    }
    if passphrase != passphrase.trim() {
        bail!("BORG_PASSPHRASE must not start or end with whitespace");
    }
    if !passphrase.chars().all(|ch| ch.is_ascii_graphic() && !matches!(ch, '{' | '}' | '%')) {
        bail!("BORG_PASSPHRASE must be printable ASCII without braces or percent signs");
    }
    Ok(())
}

/// Fills the managed passphrase when absent, preserving a passphrase already
/// stored in the local environment so re-initializing a project cannot orphan
/// its existing remote Borg repository.
///
/// # Errors
/// Returns an error when the local environment is malformed or generation fails.
pub fn ensure_backup_passphrase(backup: &mut Backup, env_path: &Path) -> Result<()> {
    if backup.is_configured() {
        return Ok(());
    }
    if let Some(existing) = read_managed_passphrase(env_path)? {
        backup.passphrase = existing;
        return Ok(());
    }
    backup.passphrase = generated_passphrase()?;
    Ok(())
}

fn read_managed_passphrase(env_path: &Path) -> Result<Option<String>> {
    let Ok(content) = fs::read_to_string(env_path) else {
        return Ok(None);
    };
    let parsed = super::local_env::parse_dotenv(&content)?;
    Ok(parsed.managed.get(PASSPHRASE_KEY).filter(|value| !value.trim().is_empty()).cloned())
}

fn generated_passphrase() -> Result<String> {
    let mut bytes = [0_u8; 24];
    getrandom::fill(&mut bytes).map_err(|error| anyhow::anyhow!("Failed to generate the Borg passphrase: {error}"))?;
    Ok(bytes.iter().map(|byte| format!("{byte:02x}")).collect())
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn default_backup_uses_the_daily_midnight_schedule_with_thirty_day_retention() {
        let backup = Backup::default();

        assert_eq!(backup.schedule, "0 0 * * *");
        assert_eq!(backup.retention_days, 30);
        assert!(!backup.is_configured());
    }

    #[test]
    fn cron_validation_accepts_standard_field_syntax() {
        for schedule in ["0 0 * * *", "*/5 * * * *", "0 3-6 * * 1-5", "30 2 1 Jan Mon", "0,15,30,45 * * * *"] {
            validate_cron_expression(schedule).unwrap_or_else(|error| panic!("{schedule}: {error}"));
        }
    }

    #[test]
    fn cron_validation_rejects_wrong_field_counts_and_unsafe_characters() {
        for schedule in ["", "0 0 * *", "0 0 * * * *", "0 0 * * *\n0 0 * * *", "0 0 * * * %", "0 0 * * * #"] {
            assert!(validate_cron_expression(schedule).is_err(), "expected rejection: {schedule:?}");
        }
    }

    #[test]
    fn backup_validation_accepts_generated_passphrases_and_rejects_hostile_values() {
        let mut backup = Backup::default();
        backup.passphrase = "a".repeat(48);
        validate_backup(&backup).expect("hex passphrase is valid");

        backup.retention_days = 0;
        assert!(validate_backup(&backup).is_err(), "zero retention must be rejected");

        backup.retention_days = 30;
        for passphrase in [" leading", "trailing ", "new\nline", "brace{{}}", "percent%", "stéphane"] {
            backup.passphrase = passphrase.to_string();
            assert!(validate_backup(&backup).is_err(), "expected rejection: {passphrase:?}");
        }
    }

    #[test]
    fn passphrase_validation_allows_unconfigured_backups() {
        let backup = Backup::default();
        validate_backup(&backup).expect("an empty passphrase means backups are unconfigured");
    }

    #[test]
    fn ensure_backup_passphrase_preserves_the_value_stored_in_the_local_environment() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join(".env");
        fs::write(&path, "BONES_BORG_PASSPHRASE=existing-value\n")?;

        let mut backup = Backup::default();
        ensure_backup_passphrase(&mut backup, &path)?;

        assert_eq!(backup.passphrase, "existing-value");
        Ok(())
    }

    #[test]
    fn ensure_backup_passphrase_generates_when_the_environment_has_none() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join(".env");
        fs::write(&path, "BONES_HOST=example.com\n")?;

        let mut backup = Backup::default();
        ensure_backup_passphrase(&mut backup, &path)?;

        assert_eq!(backup.passphrase.len(), 48);
        assert!(backup.passphrase.chars().all(|ch| ch.is_ascii_hexdigit()));
        Ok(())
    }

    #[test]
    fn ensure_backup_passphrase_treats_a_missing_environment_file_as_unconfigured() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("absent.env");

        let mut backup = Backup::default();
        ensure_backup_passphrase(&mut backup, &path)?;

        assert_eq!(backup.passphrase.len(), 48);
        Ok(())
    }
}
