---
apparmor_packages:
  - apparmor
  - apparmor-utils

apparmor_service_name: apparmor
apparmor_profile_name: "bonesdeploy-{{ project_name }}-nginx"
apparmor_profile_template_path: "{{ playbook_dir }}/../apparmor/project-nginx-profile.j2"
