template = "laravel"
web_root = "public"
php_version = "8.5"

[permissions]
paths = [
    { path = "*", type = "dir", mode = "750" },
    { path = "*", type = "file", mode = "640" },
    { path = "bootstrap/cache", type = "dir", mode = "770", recursive = true },
]
